# **PyTorch Fundamentals Exercises - Solution**



In [16]:
# Import all the necessary libraries here
import torch
import numpy as np

### **Q1 Create a random tensor with shape `(7, 7)`**


In [17]:
# Create random tensor
X = torch.rand(size=(7, 7))
X, X.shape

(tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204],
         [0.0731, 0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948],
         [0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
         [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
         [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
         [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
         [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447]]),
 torch.Size([7, 7]))

### **Q2 Perform a matrix multiplication on the tensor from Q1 with another random tensor with shape `(1, 7)`**

In [18]:
# Create another random tensor
Y = torch.rand(size=(1, 7))
Y, Y.shape

(tensor([[0.7213, 0.4414, 0.5550, 0.6361, 0.1081, 0.3305, 0.5196]]),
 torch.Size([1, 7]))

In [19]:
Z = torch.matmul(X, Y.T) # no error because of transpose
Z, Z.shape

(tensor([[1.6914],
         [1.7581],
         [2.0906],
         [1.8975],
         [1.7585],
         [1.7961],
         [1.8900]]),
 torch.Size([7, 1]))

### **Q3 Set the random seed to `0` and do Q1 & Q2 over again**

In [20]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### **Q4 Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent?**
  * If there is, set the GPU random seed to `1234`

In [21]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### **Q5 Create two random tensors of shape `(2, 3)` and send them both to the GPU. Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed)**

In [22]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### **Q6 Perform a matrix multiplication on the tensors you created in Q5**

In [23]:
# Perform matmul on tensor_A and tensor_B
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### **Q7 Find the maximum and minimum values of the output of Q6**

In [24]:
# Find max
max = torch.max(tensor_C)

# Find min
min = torch.min(tensor_C)
max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### **Q8 Find the maximum and minimum index values of the output of Q6**

In [25]:
# Find arg max
arg_max = torch.argmax(tensor_C)

# Find arg min
arg_min = torch.argmin(tensor_C)
arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

### **Q9 Perform a matrix multiplication on the tensors you created in Q5 in `numpy` and convert the output to tensor**

In [26]:
array_C = np.matmul(tensor_A.cpu().numpy(), tensor_B.cpu().numpy().T)
tensor_D = torch.from_numpy(array_C)
array_C, tensor_D, tensor_D.shape

(array([[0.36473012, 0.47088534],
        [0.51838267, 0.5617257 ]], dtype=float32),
 tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))


### **Q10 Make a random tensor with shape `(1, 1, 1, 10)` and then convert it to a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape**

In [27]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_E = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_F = tensor_E.squeeze()

# Print out tensors
print(tensor_E, tensor_E.shape)
print(tensor_F, tensor_F.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
