# **PyTorch Fundamentals Exercise**



In [ ]:
# Import all the necessary libraries here
import torch

### **Q1 Create a random tensor with shape `(7, 7)`**


In [ ]:
tensor = torch.rand(7, 7)
print(tensor)

tensor([[0.7937, 0.6414, 0.8557, 0.4398, 0.1515, 0.6923, 0.6724],
        [0.5931, 0.9442, 0.3387, 0.2812, 0.2440, 0.6945, 0.9071],
        [0.8228, 0.2694, 0.4275, 0.5419, 0.3074, 0.2858, 0.6381],
        [0.2535, 0.7374, 0.9870, 0.9759, 0.6457, 0.8740, 0.9639],
        [0.3743, 0.6017, 0.9772, 0.3823, 0.9402, 0.8318, 0.5124],
        [0.6818, 0.4178, 0.7572, 0.2346, 0.3805, 0.6869, 0.2429],
        [0.2458, 0.7664, 0.1560, 0.3509, 0.4353, 0.2049, 0.3744]])


### **Q2 Perform a matrix multiplication on the tensor from Q1 with another random tensor with shape `(1, 7)`**

In [ ]:
tensor1 = torch.rand(1,7)
print(tensor1)
torch.matmul(tensor, tensor1.T)

tensor([[0.8228, 0.4896, 0.9313, 0.3500, 0.2807, 0.7552, 0.9763]])


tensor([[3.1397],
        [2.8427],
        [2.3217],
        [3.6127],
        [3.0387],
        [2.4155],
        [1.4880]])

### **Q3 Set the random seed to `0` and do Q1 & Q2 over again**

In [ ]:
# Your code here

### **Q4 Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent?**
  * If there is, set the GPU random seed to `1234`

In [ ]:
# Your code here


### **Q5 Create two random tensors of shape `(2, 3)` and send them both to the GPU. Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed)**

In [ ]:
# Your code here


### **Q6 Perform a matrix multiplication on the tensors you created in Q5**

In [ ]:
# Your code here

### **Q7 Find the maximum and minimum values of the output of Q6**

In [ ]:
# Your code here

### **Q8 Find the maximum and minimum index values of the output of Q6**

In [ ]:
# Your code here

### **Q9 Perform a matrix multiplication on the tensors you created in Q5 in `numpy` and convert the output to tensor**

In [ ]:
# Your code here


### **Q10 Make a random tensor with shape `(1, 1, 1, 10)` and then convert it to a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape**

In [ ]:
# Your code here